#!/bin/bash

rm -r ../aoasweep
mkdir ../aoasweep

for aoa in {-16..22..2}
do
    echo Building angle: $aoa directory file.
    echo 
    echo
    python3 runcase_unstructured.py --scheme "steady"\
                                    --Reynolds 4e5\
                                    --Tu 0.31\
                                    --nu 1.1516e-5\
                                    --nuratio .1\
                                    --aoa $aoa\
                                    --c 0.45\
                                    --s 0.001\
                                    --rho 1.18\
                                    --nsteps 4500\
                                    --airfoil  "../../../airfoils/NRELs826.txt"\
                                    --savepath "../aoasweep/"\
                                    --meshcontrols ./meshcontrols/Mesh8.json 
    echo ------------------------------------------
done
