#!/bin/bash

python3 airfoilmesh.py  --airfoil ./airfoils/SD7003.txt \
                        --AoA 8. \
                        --writepath airfoil.msh \
                        --c 1 \
                        --s 0.1 \
                        --meshcontrols meshcontrols.json \