#!/bin/bash

python3 airfoilmesh.py  --airfoil ./airfoils/SG6043altered.txt \
                        --AoA 8. \
                        --writepath airfoil.msh \
                        --c 1 \
                        --s 0.1 \
                        --meshcontrols meshcontrolsfine/Mesh13.json \