#!/bin/sh

rm -r ../meshsweepcoarse
mkdir ../meshsweepcoarse

for file in `ls ./meshcontrolscoarse`
do
    echo Building $file directory file.
    echo 
    echo
    python3 runcase.py  --scheme "steady" --Reynolds 1e5 --Tu 0.94 --nu 1.1516e-5 --nuratio .1 --aoa 4. --c 1 --s 0.001 --rho 1.18 --nsteps 4750 --airfoil  "./airfoils/NRELs826.txt" --savepath "../meshsweepcoarse/" --meshcontrols ./meshcontrolscoarse/$file
    
    echo ------------------------------------------
done