#!/bin/bash

python3 structuredmesh.py   --airfoil ../../../airfoils/NRELs826altered.txt \
                            --writepath ./airfoil.msh \
                            --meshparams meshparams/meshes/mesh0.json \