#!/bin/bash

python3 airfoilmesh2.py  --airfoil ../airfoils/NRELs826altered.txt \
                        --AoA 8. \
                        --writepath airfoil.msh \
                        --c 1 \
                        --s 0.1 \
                        --meshcontrols meshcontrols/Mesh0.json \