#!/bin/bash

echo 'Running Simulation'
echo
python3 runcase_unstructured.py  --scheme   "steady"                   \
                                --Reynolds 1e5                        \
                                --Tu       0.2                      \
                                --nu       1.1516e-5                  \
                                --nuratio  0.1                        \
                                --aoa      5.0                     \
                                --c        0.1                          \
                                --s        0.01                      \
                                --rho      1.18                       \
                                --nsteps   4000                       \
                                --airfoil  "../../../airfoils/NRELs826.txt"  \
                                --savepath "../runs/"                      \
                                --meshcontrols "meshcontrols/Mesh1.json"  \
