#!/bin/sh

rm -r ../meshsweep
mkdir ../meshsweep

for file in `ls ./meshcontrols`
do
    echo Building $file directory file.
    echo 
    echo
    python3 runcase.py  --scheme "steady" --Reynolds 1e5 --Tu 0.94 --nu 1.1516e-5 --nuratio .1 --aoa 4. --c 1 --s 0.001 --rho 1.18 --nsteps 4000 --airfoil  "./airfoils/NRELs826.txt" --savepath "../meshsweep/" --meshcontrols ./meshcontrols/$file
    echo ------------------------------------------
done