#!/bin/bash

python3 airfoilmesh.py  --airfoil ../../../airfoils/NRELs826.txt    \
                        --AoA 0.                                    \
                        --writepath airfoil.msh                     \
                        --c 1.                                      \
                        --s 0.01                                    \
                        --meshcontrols meshcontrols/Mesh11.json     \